### ISSUE TITLE
Enter code window overlays tutorial button.

### ISSUE THREAD

**Issue by Chundelac** [3174N/project-dungeon-dweller#10]
Enter code window shows over the tutorial button. The dialog should overlay tutorial button instead.

1. Go to settings
2. Click on enter code

![Screenshot of bug](https://user-images.githubusercontent.com/11510682/89561004-2d5b6300-d818-11ea-99da-06355ccc5b95.png)

App version: v1.0.beta-3
Device: Pixel 3 XL

**Comment by 3174N** [comment]
Fixed.
