### ISSUE TITLE
Game broken on first start.

### ISSUE THREAD

**Issue by Chundelac** [3174N/project-dungeon-dweller#12]
The game was completely broken when it was started for the first time.

After starting the game a dialog about a chest appeared, after it a saw a tiny character and a huge one, there was walking animation while using the left thumbstick but nothing else happened so the game is unplayble further.
After restarting the whole application everything loaded correctly and I could play.

This did not happen any other time.

![Screenshot of bug](https://user-images.githubusercontent.com/11510682/89561303-980c9e80-d818-11ea-85ae-2448511cb308.png)

App version: v1.0.beta-3
Device: Pixel 3 XL

**Comment by 3174N** [comment]
Fixed.
