### ISSUE TITLE
Closed gates get drawn over the player character.

### ISSUE THREAD

**Issue by Chundelac** [3174N/project-dungeon-dweller#13]
The closed gate image is drawn over the players character even when the player should be visible over the door.

![Screenshot of bug](https://user-images.githubusercontent.com/11510682/89561514-e4f07500-d818-11ea-9ba9-42733aa403df.png)

App version: v1.0.beta-3
Device: Pixel 3 XL

**Comment by 3174N** [comment]
Fixed.
