### ISSUE TITLE
Invisible enemies

### ISSUE THREAD

**Issue by Chundelac** [3174N/project-dungeon-dweller#14]
Enemies can be completely invisible when looking vertically.

There is an enemy on the following screenshot under the player looking up, the health bar is visible but enemy is not.
![Screenshot of bug](https://user-images.githubusercontent.com/11510682/89561707-2ed95b00-d819-11ea-8d0d-3a369549cd5f.png)

App version: v1.0.beta-3
Device: Pixel 3 XL

**Comment by 3174N** [comment]
Fixed.
