### ISSUE TITLE
Adaptive app icon.

### ISSUE THREAD

**Issue by Chundelac** [3174N/project-dungeon-dweller#8]
The app uses a static icon in square shape. This causes the icon to not displayed properly on devices using different icon shape.
In this apps case it causes the dragons head to be extremely small compared to the rest of the icon space

All apps should provide an adaptive app icon that allows the OS to chose the icons shape.

[Related android docs.](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive)

App version: v1.0.beta-3
Device: Pixel 3 XL

**Comment by 3174N** [comment]
Fixed.
