### ISSUE TITLE
Game visible on the edges of settings screen.

### ISSUE THREAD

**Issue by Chundelac** [3174N/project-dungeon-dweller#9]
While the settings are open a few pixels of the background game are still visible on all sides.

1. Go to main menu
2. Click on settings
3. The very edges of screen show the main menu background

If this is intended it should show more than a few pixels.

![Screenshot of the bug](https://user-images.githubusercontent.com/11510682/89560695-b756fc00-d817-11ea-9445-4f68b5145282.png)

App version: v1.0.beta-3
Device: Pixel 3 XL

**Comment by 3174N** [comment]
Fixed.
